### ISSUE TITLE
add-github-project command doesn't write to riak

### ISSUE THREAD

**Issue by konklone** [18F/Sendak#78]
During our testing this morning, it required manual intervention to save data to riak.

**Comment by janearc** [comment]
so after looking at rrm the bug doesn't seem to be there.

**Comment by janearc** [comment]
JANE SMASH.
![jane-annoyed](https://cloud.githubusercontent.com/assets/777319/5877949/341de648-a2f1-11e4-8d0b-11dfad2898cf.png)
